### ISSUE TITLE
handling floats for tolerance

### ISSUE THREAD

**Issue by kcivey** [andreychumak/simplify-php#1]
<a href="https://github.com/andreychumak/simplify-php/blob/master/Simplify.php#L24">This line</a> seems to be a mistranslation of the JavaScript version:

```
$sqTolerance = (int)$tolerance == $tolerance ? $tolerance*$tolerance : 1;
```

If a float is passed for $tolerance, then it will be ignored and the default value of 1 will be used instead. Shouldn't it just be this?

```
$sqTolerance = $tolerance * $tolerance;
```

The test in the JavaScript original is just to handle the default value, but PHP handles that automatically.

**Comment by jakezatecky** [comment]
+1

**Comment by andriichumak** [comment]
Valid point, fixed that in last commit
