### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in Simplify.php on line 69

### ISSUE THREAD

**Issue by wrhwebmaster** [andreychumak/simplify-php#2]
I grabbed the latest zip package.
when I test "test.php" I get an error, similar to when I test the main PHP script:
PHP Parse error:  syntax error, unexpected '[' in Simplify.php on line 69

**Comment by andriichumak** [comment]
Hi, @wrhwebmaster 
I left a few lines with short array syntax, that's why on php < 5.4 it would cause error. Fixed with last commit.
