### ISSUE TITLE
Divide by zero warnings

### ISSUE THREAD

**Issue by dchaffin** [andreychumak/simplify-php#4]
I was getting all kinds of divide by zero warnings until I changed line 112 from:

if ($dx !== 0 || $dy !== 0) {

... to:

if (intval($dx) !== 0 || intval($dy) !== 0) {
 --- or --- 
if ($dx !== 0.0 || $dy !== 0.0) {

**Comment by andriichumak** [comment]
Thanks, fixed in 1.0.2.
